// <auto-generated />
namespace Padaria_Rick.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nomes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nomes));
        
        string IMigrationMetadata.Id
        {
            get { return "201907011933482_nomes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
